'''
Made By: Talita James
Last Updated: 14/01/2025

Takes MCTS .json files generated by battleship code,
to analyse and display the tree structure
'''

import json
import networkx as nx
import matplotlib.pyplot as plt

def get_tree_strings(filename):
    '''Get the list of trees at each turn given a filename'''
    with open(filename) as f:
        gameHistory = json.load(f)
    return gameHistory["treeRecord"]


def turn_treestring_into_list(treestring):
    '''Given a single turns tree string, split it into
    a list of tupples [(from1, to1), (from2, to2)...]
    '''
    treelist = treestring.split('\n')
    treeTuppleList = []

    for value in treelist:
        if value != '':
            treeTuppleList.append(tuple(value.split(" --> ")))

    return treeTuppleList


def make_tree(treestring):
    '''Given a string, convert it into a networkx graph'''
    Graph = nx.DiGraph()
    edgeList = turn_treestring_into_list(treestring)
    Graph.add_edges_from(edgeList)

    return Graph


def view_tree(Graph):
    '''Display a graph'''
    pos = nx.bfs_layout(Graph, list(G.nodes)[0])
    nx.draw(Graph, pos=pos) #, with_labels=True, font_weight='bold')
    plt.show() #FIXME, return or save the image rather than showing
    pass


def graph_stats(Graph):
    '''Give information about graph size etc'''
    return f"Nodes:{Graph.number_of_nodes()},Edges:{Graph.number_of_edges()}"


if __name__=="__main__":
    filename = "out/gamePlay/8_3_1779043_MCTS_v4_zdGTTZ.json" # MCTS file to read in
    gameTreeList = get_tree_strings(filename)

    for x in [3]: #range(len(gameTreeList)):
        G = make_tree(gameTreeList[x])
        print(f"Turn {x} has {graph_stats(G)}")
        view_tree(G) #Note that viewing large trees takes long times